### ISSUE TITLE
call fetchAll() on InMemoryStorage as first method creates an empty stream

### ISSUE THREAD

**Issue by luckv** [marcelgarus/repository#2]
If I create an _InMemoryStorage_ repository and then I call _fetchAll()_, _fetchAllIds()_ of _fetchAllItems()_ as first method call, the stream returned is empty and if i try to get the first element i get a pending future that never complete until I call _update()_ or _remove()_ on the repositiory. This is because initially the _**_allEntriesController**_ _BehaviourSubject_ is empty and only if I call _update()_ or _remove()_ on the repository the BehaviourSubject is not empty.
The solution is simple, put an initial empty map on __allEntriesController_.

**Comment by MarcelGarus** [comment]
You're right, and thank you for the PR. Happy holidays!
